const songs = [
	{
		data: {
			kind: 'youtube#videoListResponse',
			etag: 'x1lVMZHn2I2Jn9Ji9ECsX-N3ecE',
			items: [
				{
					kind: 'youtube#video',
					etag: 'zEwI5fn0p9dIldzR7TLS5f6XbLw',
					id: 'iGaF4tKUl0o',
					snippet: {
						publishedAt: '2012-09-03T01:37:22Z',
						channelId: 'UCWO9OCjghM_d8Q5MDKNK7oQ',
						title: "Chris Norman & Suzi Quatro - Stumblin' In 1978",
						description:
							'New higher quality version - https://www.youtube.com/watch?v=eL4WKABH4NM',
						thumbnails: {
							default: {
								url: 'https://i.ytimg.com/vi/iGaF4tKUl0o/default.jpg',
								width: 120,
								height: 90,
							},
							medium: {
								url: 'https://i.ytimg.com/vi/iGaF4tKUl0o/mqdefault.jpg',
								width: 320,
								height: 180,
							},
							high: {
								url: 'https://i.ytimg.com/vi/iGaF4tKUl0o/hqdefault.jpg',
								width: 480,
								height: 360,
							},
							standard: {
								url: 'https://i.ytimg.com/vi/iGaF4tKUl0o/sddefault.jpg',
								width: 640,
								height: 480,
							},
						},
						channelTitle: 'NoMadU55555',
						tags: [
							'Chris Norman',
							'Suzi Quatro',
							'Chris Norman & Suzi Quatro',
							"Stumblin' In",
							'Oldies',
						],
						categoryId: '10',
						liveBroadcastContent: 'none',
						localized: {
							title: "Chris Norman & Suzi Quatro - Stumblin' In 1978",
							description:
								'New higher quality version - https://www.youtube.com/watch?v=eL4WKABH4NM',
						},
					},
					statistics: {
						viewCount: '217002869',
						likeCount: '732732',
						dislikeCount: '35346',
						favoriteCount: '0',
						commentCount: '35083',
					},
				},
			],
			pageInfo: { totalResults: 1, resultsPerPage: 1 },
		},
		status: 200,
		statusText: '',
		headers: {
			'cache-control': 'private',
			'content-type': 'application/json; charset=UTF-8',
			date: 'Sat, 29 May 2021 16:48:59 GMT',
			server: 'scaffolding on HTTPServer2',
			vary: 'Origin, X-Origin, Referer',
		},
		config: {
			url: '/videos',
			method: 'get',
			headers: { Accept: 'application/json, text/plain, */*' },
			params: {
				part: 'snippet, statistics',
				maxResults: 5,
				key: 'AIzaSyCPFR-b3vldvPYvj2qZdcM_W44PkHZ8dcc',
				id: 'iGaF4tKUl0o',
			},
			baseURL: 'https://www.googleapis.com/youtube/v3/',
			transformRequest: [null],
			transformResponse: [null],
			timeout: 0,
			xsrfCookieName: 'XSRF-TOKEN',
			xsrfHeaderName: 'X-XSRF-TOKEN',
			maxContentLength: -1,
			maxBodyLength: -1,
		},
		request: {},
	},
	{
		data: {
			kind: 'youtube#videoListResponse',
			etag: 'WronnPOujNgD3ut9lz-uJOqYHp0',
			items: [
				{
					kind: 'youtube#video',
					etag: 'V3FZLOSnk2iw31lLVl_lvcG6kXA',
					id: 'xYoogY-UGio',
					snippet: {
						publishedAt: '2010-05-13T07:48:42Z',
						channelId: 'UCBVjhbfg2wQkhxgzyGTljvQ',
						title: 'Suzi Quatro - Can The Can (1973)',
						description: 'http://www.suziquatro.com/',
						thumbnails: {
							default: {
								url: 'https://i.ytimg.com/vi/xYoogY-UGio/default.jpg',
								width: 120,
								height: 90,
							},
							medium: {
								url: 'https://i.ytimg.com/vi/xYoogY-UGio/mqdefault.jpg',
								width: 320,
								height: 180,
							},
							high: {
								url: 'https://i.ytimg.com/vi/xYoogY-UGio/hqdefault.jpg',
								width: 480,
								height: 360,
							},
						},
						channelTitle: 'kiilakas777',
						tags: ['Suzi', 'Quatro', 'Can', 'The', 'Can', '1973'],
						categoryId: '10',
						liveBroadcastContent: 'none',
						localized: {
							title: 'Suzi Quatro - Can The Can (1973)',
							description: 'http://www.suziquatro.com/',
						},
					},
					statistics: {
						viewCount: '31782276',
						likeCount: '92507',
						dislikeCount: '3212',
						favoriteCount: '0',
						commentCount: '4505',
					},
				},
			],
			pageInfo: { totalResults: 1, resultsPerPage: 1 },
		},
		status: 200,
		statusText: '',
		headers: {
			'cache-control': 'private',
			'content-type': 'application/json; charset=UTF-8',
			date: 'Sat, 29 May 2021 16:48:59 GMT',
			server: 'scaffolding on HTTPServer2',
			vary: 'Origin, X-Origin, Referer',
		},
		config: {
			url: '/videos',
			method: 'get',
			headers: { Accept: 'application/json, text/plain, */*' },
			params: {
				part: 'snippet, statistics',
				maxResults: 5,
				key: 'AIzaSyCPFR-b3vldvPYvj2qZdcM_W44PkHZ8dcc',
				id: 'xYoogY-UGio',
			},
			baseURL: 'https://www.googleapis.com/youtube/v3/',
			transformRequest: [null],
			transformResponse: [null],
			timeout: 0,
			xsrfCookieName: 'XSRF-TOKEN',
			xsrfHeaderName: 'X-XSRF-TOKEN',
			maxContentLength: -1,
			maxBodyLength: -1,
		},
		request: {},
	},
	{
		data: {
			kind: 'youtube#videoListResponse',
			etag: '-pfrWjQ7Qiyg-HxpO9LaUFjnjKQ',
			items: [
				{
					kind: 'youtube#video',
					etag: 'KM2j5G8VvdWrzLZXCMoI60-Bc_4',
					id: 'SeI42SvFy7Y',
					snippet: {
						publishedAt: '2018-02-01T10:58:03Z',
						channelId: 'UCWO9OCjghM_d8Q5MDKNK7oQ',
						title:
							"Suzi Quatro - If You Can't Give Me Love 1978 (HQ, Ein Kessel Buntes)",
						description: 'BEST QUALITY SOUND AND VIDEO. :)',
						thumbnails: {
							default: {
								url: 'https://i.ytimg.com/vi/SeI42SvFy7Y/default.jpg',
								width: 120,
								height: 90,
							},
							medium: {
								url: 'https://i.ytimg.com/vi/SeI42SvFy7Y/mqdefault.jpg',
								width: 320,
								height: 180,
							},
							high: {
								url: 'https://i.ytimg.com/vi/SeI42SvFy7Y/hqdefault.jpg',
								width: 480,
								height: 360,
							},
							standard: {
								url: 'https://i.ytimg.com/vi/SeI42SvFy7Y/sddefault.jpg',
								width: 640,
								height: 480,
							},
						},
						channelTitle: 'NoMadU55555',
						tags: ['nostalgie', 'golden', 'oldies'],
						categoryId: '10',
						liveBroadcastContent: 'none',
						localized: {
							title:
								"Suzi Quatro - If You Can't Give Me Love 1978 (HQ, Ein Kessel Buntes)",
							description: 'BEST QUALITY SOUND AND VIDEO. :)',
						},
					},
					statistics: {
						viewCount: '36065090',
						likeCount: '145777',
						dislikeCount: '5927',
						favoriteCount: '0',
						commentCount: '5412',
					},
				},
			],
			pageInfo: { totalResults: 1, resultsPerPage: 1 },
		},
		status: 200,
		statusText: '',
		headers: {
			'cache-control': 'private',
			'content-type': 'application/json; charset=UTF-8',
			date: 'Sat, 29 May 2021 16:48:59 GMT',
			server: 'scaffolding on HTTPServer2',
			vary: 'Origin, X-Origin, Referer',
		},
		config: {
			url: '/videos',
			method: 'get',
			headers: { Accept: 'application/json, text/plain, */*' },
			params: {
				part: 'snippet, statistics',
				maxResults: 5,
				key: 'AIzaSyCPFR-b3vldvPYvj2qZdcM_W44PkHZ8dcc',
				id: 'SeI42SvFy7Y',
			},
			baseURL: 'https://www.googleapis.com/youtube/v3/',
			transformRequest: [null],
			transformResponse: [null],
			timeout: 0,
			xsrfCookieName: 'XSRF-TOKEN',
			xsrfHeaderName: 'X-XSRF-TOKEN',
			maxContentLength: -1,
			maxBodyLength: -1,
		},
		request: {},
	},
	{
		data: {
			kind: 'youtube#videoListResponse',
			etag: 'ofOjHhk6aWrL55tTEbK0KXPcdtE',
			items: [
				{
					kind: 'youtube#video',
					etag: 'BcGR7bQdJVGAIt-ydz7AzupJIwU',
					id: 'eL4WKABH4NM',
					snippet: {
						publishedAt: '2018-01-12T15:39:42Z',
						channelId: 'UCWO9OCjghM_d8Q5MDKNK7oQ',
						title:
							"Chris Norman & Suzi Quatro - Stumblin' In 1978 (New High Quality Version)",
						description:
							'New higher quality version. The video with this song was one of the first my uploads on Youtube. This version is slightly modified for better synchronization.',
						thumbnails: {
							default: {
								url: 'https://i.ytimg.com/vi/eL4WKABH4NM/default.jpg',
								width: 120,
								height: 90,
							},
							medium: {
								url: 'https://i.ytimg.com/vi/eL4WKABH4NM/mqdefault.jpg',
								width: 320,
								height: 180,
							},
							high: {
								url: 'https://i.ytimg.com/vi/eL4WKABH4NM/hqdefault.jpg',
								width: 480,
								height: 360,
							},
							standard: {
								url: 'https://i.ytimg.com/vi/eL4WKABH4NM/sddefault.jpg',
								width: 640,
								height: 480,
							},
						},
						channelTitle: 'NoMadU55555',
						tags: ['nostalgie', 'golden', 'oldies'],
						categoryId: '10',
						liveBroadcastContent: 'none',
						localized: {
							title:
								"Chris Norman & Suzi Quatro - Stumblin' In 1978 (New High Quality Version)",
							description:
								'New higher quality version. The video with this song was one of the first my uploads on Youtube. This version is slightly modified for better synchronization.',
						},
					},
					statistics: {
						viewCount: '6792367',
						likeCount: '38757',
						dislikeCount: '1805',
						favoriteCount: '0',
						commentCount: '1798',
					},
				},
			],
			pageInfo: { totalResults: 1, resultsPerPage: 1 },
		},
		status: 200,
		statusText: '',
		headers: {
			'cache-control': 'private',
			'content-type': 'application/json; charset=UTF-8',
			date: 'Sat, 29 May 2021 16:48:59 GMT',
			server: 'scaffolding on HTTPServer2',
			vary: 'Origin, X-Origin, Referer',
		},
		config: {
			url: '/videos',
			method: 'get',
			headers: { Accept: 'application/json, text/plain, */*' },
			params: {
				part: 'snippet, statistics',
				maxResults: 5,
				key: 'AIzaSyCPFR-b3vldvPYvj2qZdcM_W44PkHZ8dcc',
				id: 'eL4WKABH4NM',
			},
			baseURL: 'https://www.googleapis.com/youtube/v3/',
			transformRequest: [null],
			transformResponse: [null],
			timeout: 0,
			xsrfCookieName: 'XSRF-TOKEN',
			xsrfHeaderName: 'X-XSRF-TOKEN',
			maxContentLength: -1,
			maxBodyLength: -1,
		},
		request: {},
	},
	{
		data: {
			kind: 'youtube#videoListResponse',
			etag: 'YIG8buIpXnWIxWfBGd7sn_LGjk8',
			items: [
				{
					kind: 'youtube#video',
					etag: 'JD4jv01t2u8rjgUzAE0ox5rRx6s',
					id: 'bEHBzbWK79w',
					snippet: {
						publishedAt: '2018-06-09T05:38:45Z',
						channelId: 'UCWO9OCjghM_d8Q5MDKNK7oQ',
						title: "Suzi Quatro - She's In Love With You 1979 (High Quality)",
						description: 'BEST QUALITY SOUND AND VIDEO. :)',
						thumbnails: {
							default: {
								url: 'https://i.ytimg.com/vi/bEHBzbWK79w/default.jpg',
								width: 120,
								height: 90,
							},
							medium: {
								url: 'https://i.ytimg.com/vi/bEHBzbWK79w/mqdefault.jpg',
								width: 320,
								height: 180,
							},
							high: {
								url: 'https://i.ytimg.com/vi/bEHBzbWK79w/hqdefault.jpg',
								width: 480,
								height: 360,
							},
							standard: {
								url: 'https://i.ytimg.com/vi/bEHBzbWK79w/sddefault.jpg',
								width: 640,
								height: 480,
							},
						},
						channelTitle: 'NoMadU55555',
						tags: ['nostalgie', 'golden', 'oldies'],
						categoryId: '10',
						liveBroadcastContent: 'none',
						localized: {
							title: "Suzi Quatro - She's In Love With You 1979 (High Quality)",
							description: 'BEST QUALITY SOUND AND VIDEO. :)',
						},
					},
					statistics: {
						viewCount: '5006301',
						likeCount: '27494',
						dislikeCount: '888',
						favoriteCount: '0',
						commentCount: '933',
					},
				},
			],
			pageInfo: { totalResults: 1, resultsPerPage: 1 },
		},
		status: 200,
		statusText: '',
		headers: {
			'cache-control': 'private',
			'content-type': 'application/json; charset=UTF-8',
			date: 'Sat, 29 May 2021 16:48:59 GMT',
			server: 'scaffolding on HTTPServer2',
			vary: 'Origin, X-Origin, Referer',
		},
		config: {
			url: '/videos',
			method: 'get',
			headers: { Accept: 'application/json, text/plain, */*' },
			params: {
				part: 'snippet, statistics',
				maxResults: 5,
				key: 'AIzaSyCPFR-b3vldvPYvj2qZdcM_W44PkHZ8dcc',
				id: 'bEHBzbWK79w',
			},
			baseURL: 'https://www.googleapis.com/youtube/v3/',
			transformRequest: [null],
			transformResponse: [null],
			timeout: 0,
			xsrfCookieName: 'XSRF-TOKEN',
			xsrfHeaderName: 'X-XSRF-TOKEN',
			maxContentLength: -1,
			maxBodyLength: -1,
		},
		request: {},
	},
];
